[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/databyjp/axi_da_transform_demos/blob/main/DAT2_Week_3_1.ipynb)
# DA Transform - Week 3 session 1

## Review

### Nested loops

Let's fetch all reviewes which have had at least one vote marked "helpful".

In [1]:
reviews = [
  {"reviewerID": "A2IBPI20UZIR0U", "asin": "1384719342", "reviewerName": "cassandra tu \"Yeah, well, that's just like, u...", "helpful": [0, 0], "reviewText": "Not much to write about here, but it does exactly what it's supposed to. filters out the pop sounds. now my recordings are much more crisp. it is one of the lowest prices pop filters on amazon so might as well buy it, they honestly work the same despite their pricing,", "overall": 5.0, "summary": "good", "unixReviewTime": 1393545600, "reviewTime": "02 28, 2014"},
  {"reviewerID": "A14VAT5EAX3D9S", "asin": "1384719342", "reviewerName": "Jake", "helpful": [13, 14], "reviewText": "The product does exactly as it should and is quite affordable.I did not realized it was double screened until it arrived, so it was even better than I had expected.As an added bonus, one of the screens carries a small hint of the smell of an old grape candy I used to buy, so for reminiscent's sake, I cannot stop putting the pop filter next to my nose and smelling it after recording. :DIf you needed a pop filter, this will work just as well as the expensive ones, and it may even come with a pleasing aroma like mine did!Buy this product! :]", "overall": 5.0, "summary": "Jake", "unixReviewTime": 1363392000, "reviewTime": "03 16, 2013"},
  {"reviewerID": "A195EZSQDW3E21", "asin": "1384719342", "reviewerName": "Rick Bennette \"Rick Bennette\"", "helpful": [1, 1], "reviewText": "The primary job of this device is to block the breath that would otherwise produce a popping sound, while allowing your voice to pass through with no noticeable reduction of volume or high frequencies. The double cloth filter blocks the pops and lets the voice through with no coloration. The metal clamp mount attaches to the mike stand secure enough to keep it attached. The goose neck needs a little coaxing to stay where you put it.", "overall": 5.0, "summary": "It Does The Job Well", "unixReviewTime": 1377648000, "reviewTime": "08 28, 2013"},
  {"reviewerID": "A2C00NNG1ZQQG2", "asin": "1384719342", "reviewerName": "RustyBill \"Sunday Rocker\"", "helpful": [0, 0], "reviewText": "Nice windscreen protects my MXL mic and prevents pops. Only thing is that the gooseneck is only marginally able to hold the screen in position and requires careful positioning of the clamp to avoid sagging.", "overall": 5.0, "summary": "GOOD WINDSCREEN FOR THE MONEY", "unixReviewTime": 1392336000, "reviewTime": "02 14, 2014"},
  {"reviewerID": "A94QU4C90B1AX", "asin": "1384719342", "reviewerName": "SEAN MASLANKA", "helpful": [0, 0], "reviewText": "This pop filter is great. It looks and performs like a studio filter. If you're recording vocals this will eliminate the pops that gets recorded when you sing.", "overall": 5.0, "summary": "No more pops when I record my vocals.", "unixReviewTime": 1392940800, "reviewTime": "02 21, 2014"},
  {"reviewerID": "A2A039TZMZHH9Y", "asin": "B00004Y2UT", "reviewerName": "Bill Lewey \"blewey\"", "helpful": [0, 0], "reviewText": "So good that I bought another one.  Love the heavy cord and gold connectors.  Bass sounds great.  I just learned last night how to coil them up.  I guess I should read instructions more carefully.  But no harm done, still works great!", "overall": 5.0, "summary": "The Best Cable", "unixReviewTime": 1356048000, "reviewTime": "12 21, 2012"},
  {"reviewerID": "A1UPZM995ZAH90", "asin": "B00004Y2UT", "reviewerName": "Brian", "helpful": [0, 0], "reviewText": "I have used monster cables for years, and with good reason. The lifetime warranty is worth the price alone. Simple fact: cables break, but getting to replace them at no cost is where it's at.", "overall": 5.0, "summary": "Monster Standard 100 - 21' Instrument Cable", "unixReviewTime": 1390089600, "reviewTime": "01 19, 2014"},
  {"reviewerID": "AJNFQI3YR6XJ5", "asin": "B00004Y2UT", "reviewerName": "Fender Guy \"Rick\"", "helpful": [0, 0], "reviewText": "I now use this cable to run from the output of my pedal chain to the input of my Fender Amp. After I bought Monster Cable to hook up my pedal board I thought I would try another one and update my guitar. I had been using a high end Planet Waves cable that I bought in the 1980's... Once I found out the input jacks on the new Monster cable didn't fit into the Fender Strat jack I was a little disappointed... I didn't return it and as stated I use it for the output on the pedal board. Save your money... I went back to my Planet Waves Cable...I payed $30.00 back in the eighties for the Planet Waves which now comes in at around $50.00. What I'm getting at is you get what you pay for. I thought Waves was a lot of money back in the day...but I haven't bought a guitar cable since this one...20 plus years and still working...Planet Waves wins.", "overall": 3.0, "summary": "Didn't fit my 1996 Fender Strat...", "unixReviewTime": 1353024000, "reviewTime": "11 16, 2012"},
  {"reviewerID": "A3M1PLEYNDEYO8", "asin": "B00004Y2UT", "reviewerName": "G. Thomas \"Tom\"", "helpful": [0, 0], "reviewText": "Perfect for my Epiphone Sheraton II.  Monster cables are well constructed.  I have several and never had any problems with any of them over the years.  Got this one because I wanted the 90 degree plug.", "overall": 5.0, "summary": "Great cable", "unixReviewTime": 1215302400, "reviewTime": "07 6, 2008"},
  {"reviewerID": "AMNTZU1YQN1TH", "asin": "B00004Y2UT", "reviewerName": "Kurt Robair", "helpful": [0, 0], "reviewText": "Monster makes the best cables and a lifetime warranty doesnt hurt either. This isnt their top of the line series but it works great with my bass guitar rig and has for some time. You cant go wrong with Monster Cables.", "overall": 5.0, "summary": "Best Instrument Cables On The Market", "unixReviewTime": 1389139200, "reviewTime": "01 8, 2014"},
  {"reviewerID": "A2NYK9KWFMJV4Y", "asin": "B00004Y2UT", "reviewerName": "Mike Tarrani \"Jazz Drummer\"", "helpful": [6, 6], "reviewText": "Monster makes a wide array of cables, including some that are very high end. I initially purchased a pair ofMonster Rock Instrument Cable - 21 Feet - Angled to Straight 1/4-Inch plugto use with my keyboards, but when it came time to purchase cables for my bass and guitar I thought I'd pinch a few pennies.  I am so glad I did.I compared this cable model to the more expensive models I previously purchased and, aside from looks, could not detect any difference in sound. I Swapped back and forth between my guitars and keyboards, ensuring that each model was used on each instrument - still no difference.What the more expensive model has going for it is looks. I am not sure it (the higher priced model) is even more sturdy because the molded stress relief ends on this model seem to make it more reliable than its pricier sibling.Bottom line: carefully compare both cables using your own instrument and amp - if possible - before making a purchase decision. You may find, as I did, that higher price does not necessarily equal higher value, even from the same manufacturer.", "overall": 5.0, "summary": "One of the best instrument cables within the brand", "unixReviewTime": 1334793600, "reviewTime": "04 19, 2012"},
  {"reviewerID": "A35QFQI0M46LWO", "asin": "B00005ML71", "reviewerName": "Christopher C", "helpful": [0, 0], "reviewText": "I got it to have it if I needed it. I have found that i don't really need it that often and rarely use it. If I was really good I can see the need. But this is a keyboard not an organ.", "overall": 4.0, "summary": "It works great but I hardly use it.", "unixReviewTime": 1398124800, "reviewTime": "04 22, 2014"},
  {"reviewerID": "A2NIT6BKW11XJQ", "asin": "B00005ML71", "reviewerName": "Jai", "helpful": [0, 0], "reviewText": "If you are not use to using a large sustaining pedal while playing the piano, it may appear little awkward.", "overall": 3.0, "summary": "HAS TO GET USE TO THE SIZE", "unixReviewTime": 1384646400, "reviewTime": "11 17, 2013"},
  {"reviewerID": "A1C0O09LOLVI39", "asin": "B00005ML71", "reviewerName": "Michael", "helpful": [0, 0], "reviewText": "I love it, I used this for my Yamaha ypt-230 and it works great, I would recommend it to anyone", "overall": 5.0, "summary": "awesome", "unixReviewTime": 1371340800, "reviewTime": "06 16, 2013"},
  {"reviewerID": "A17SLR18TUMULM", "asin": "B00005ML71", "reviewerName": "Straydogger", "helpful": [0, 0], "reviewText": "I bought this to use in my home studio to control my midi keyboard. It does just what I wanted it to do.", "overall": 5.0, "summary": "It works!", "unixReviewTime": 1356912000, "reviewTime": "12 31, 2012"},
  {"reviewerID": "A2PD27UKAD3Q00", "asin": "B00005ML71", "reviewerName": "Wilhelmina Zeitgeist \"coolartsybabe\"", "helpful": [0, 0], "reviewText": "I bought this to use with my keyboard. I wasn't really aware that there were other options for keyboard pedals. It doesn't work as smoothly as the pedals do on an acoustic piano, which is what I'd always used. Doesn't have the same feel either. Nowhere close.In my opinion, a sustain pedal like the M-Audio SP-2 Sustain Pedal with Piano Style Action or other similar pedal is a much better choice. The price difference is only a few dollars and the feel and action are so much better. The only thing I've found the Yamaha FC-5 Sustain Pedal is good for is taking up space in a drawer where I keep my electric guitar pedals.", "overall": 2.0, "summary": "Definitely Not For The Seasoned Piano Player", "unixReviewTime": 1376697600, "reviewTime": "08 17, 2013"},
  {"reviewerID": "AKSFZ4G1AXYFC", "asin": "B000068NSX", "reviewerName": "C.E. \"Frank\"", "helpful": [0, 0], "reviewText": "This Fender cable is the perfect length for me! Sometimes I find it a bit too long but I don't mind. The build quality is great and I know that it will last. The only gripe I have with this cable is that the metal sleeve gets unscrewed way too easily, requiring me to tighten it often.Sound quality is not affected, and the color is cool, definitely try this cable out.", "overall": 4.0, "summary": "Durable Instrument Cable", "unixReviewTime": 1376352000, "reviewTime": "08 13, 2013"},
  {"reviewerID": "A67OJZLHBBUQ9", "asin": "B000068NSX", "reviewerName": "Charles F. Marks \"charlie marks\"", "helpful": [0, 0], "reviewText": "wanted it just on looks alone...It is a nice looking cord... I know it will perform...as for Sam Ash ...this cord was packed in a mailer inside another box with my Roc n Soc... his shipping team do great work..never any complaints from me... I love Sam Ash.. thanks Amazon", "overall": 5.0, "summary": "fender 18 ft. Cali clear...", "unixReviewTime": 1373328000, "reviewTime": "07 9, 2013"},
  {"reviewerID": "A2EZWZ8MBEDOLN", "asin": "B000068NSX", "reviewerName": "Charlo", "helpful": [3, 3], "reviewText": "I've been using these cables for more than 4 months and they are holding up pretty well.  For years I used seemingly indestructable guitar cables that were made for me by an electrician friend.  When they finally gave out, I got in the habit of using the no-name cables that are always on display near the register at Guitar Center- really more of an impulse buy than something I put any thought into.  After the third or fourth Guitar Center cable failed from light use I decided to try these cables.  Not only are they cheaper but they seem to be holding up better.  I am not terribly hard on my gear but my cables tend to get twisted as I move around and the cheaper ones  eventually fail mid-cable.  I don't mind spending a few extra dollars if the cable is a little more durable.  This cable is actually cheaper- $12 or so shipped- and it's holding up pretty well.  These are actually very reasonably priced for 18' cables.  There is some kind of limited life warantee on this product but I haven't needed it.  Five stars for a nicely made 18 foot guitar cable that costs $12 shipped!Incidentally- these cables are shielded and are meant to connect your instrument to your amp's input.  Do not use these to connect an amplifier to a speaker cab.  You want to use unshielded cables for that purpose.Edit-  More than 6 months has passed and this cable is functioning without any issues.  The price on these things has gone up significantly and although the cable is highly recommended, there are probably better values from Hosa, Monster or Planet Waves-", "overall": 5.0, "summary": "So far so good.  Will revisit at the 6 month mark ;)", "unixReviewTime": 1363564800, "reviewTime": "03 18, 2013"},
  {"reviewerID": "A1CL807EOUPVP1", "asin": "B000068NSX", "reviewerName": "GunHawk", "helpful": [0, 0], "reviewText": "Fender cords look great and work just as well. By adding the word California to the description I'm sure to sound like the Beach Boys...", "overall": 5.0, "summary": "Add California to the name and I jump!", "unixReviewTime": 1375833600, "reviewTime": "08 7, 2013"},
]

In [2]:
review = reviews[0]
print(review['helpful'][0])  # N votes marked "helpful"

0


In [3]:
pos_reviews = list()
for review in reviews:
  n_votes = review['helpful'][0]
  # print(n_votes)
  if n_votes > 0:
    pos_reviews.append(review)
print(pos_reviews)
print(len(pos_reviews))

[{'reviewerID': 'A14VAT5EAX3D9S', 'asin': '1384719342', 'reviewerName': 'Jake', 'helpful': [13, 14], 'reviewText': "The product does exactly as it should and is quite affordable.I did not realized it was double screened until it arrived, so it was even better than I had expected.As an added bonus, one of the screens carries a small hint of the smell of an old grape candy I used to buy, so for reminiscent's sake, I cannot stop putting the pop filter next to my nose and smelling it after recording. :DIf you needed a pop filter, this will work just as well as the expensive ones, and it may even come with a pleasing aroma like mine did!Buy this product! :]", 'overall': 5.0, 'summary': 'Jake', 'unixReviewTime': 1363392000, 'reviewTime': '03 16, 2013'}, {'reviewerID': 'A195EZSQDW3E21', 'asin': '1384719342', 'reviewerName': 'Rick Bennette "Rick Bennette"', 'helpful': [1, 1], 'reviewText': 'The primary job of this device is to block the breath that would otherwise produce a popping sound, whil

Indentation matters - a lot!

### Functions

Let's build a function which will print a random review from this list, where the review text is capitalised randomly (like a classic movie-trope ransom note!)

We will use the `randrange` function (docs: https://docs.python.org/3/library/random.html)

In [5]:
import random

def get_rand_review():
  rand_ind = random.randrange(0, len(reviews))
  rand_review = reviews[rand_ind]
  rand_review_body = rand_review['reviewText']
  return rand_review_body  # Try 'return rand_ind' or 'return rand_review' instead of 'return rand_review_body'

get_rand_review()

"I bought this to use with my keyboard. I wasn't really aware that there were other options for keyboard pedals. It doesn't work as smoothly as the pedals do on an acoustic piano, which is what I'd always used. Doesn't have the same feel either. Nowhere close.In my opinion, a sustain pedal like the M-Audio SP-2 Sustain Pedal with Piano Style Action or other similar pedal is a much better choice. The price difference is only a few dollars and the feel and action are so much better. The only thing I've found the Yamaha FC-5 Sustain Pedal is good for is taking up space in a drawer where I keep my electric guitar pedals."

In [6]:
def name_builder():
  names = list()
  firsts = ['James', 'Janice', 'Sally']
  lasts = ['Smith', 'Wu']
  for last in lasts:
    print('last name', last)
    for first in firsts:
      print('Now processing first name', first)
      name = first + ' ' + last
      names.append(name)
      # print('Current list inside loops', names)
  return names

print('Final output', name_builder())

last name Smith
Now processing first name James
Now processing first name Janice
Now processing first name Sally
last name Wu
Now processing first name James
Now processing first name Janice
Now processing first name Sally
Final output ['James Smith', 'Janice Smith', 'Sally Smith', 'James Wu', 'Janice Wu', 'Sally Wu']


### Arguments in functions

In [7]:
def name_builder(firsts, lasts):
  names = list()
  for last in lasts:
    for first in firsts:
      name = first + ' ' + last
      names.append(name)
  return names

print('Final output', name_builder(['james'], ['wu', 'smith']))

Final output ['james wu', 'james smith']


### Debugging code

- Take a look at the error message
- Try to identify where the error is occurring
- Work through the state of the program up to that point
  - print statements are your friends!

In [8]:
tmp_list = list(range(5))
for i in tmp_list:
  # print(i)
  # print(type(i))
  print(i + 'str')  # Look at the error message - and then add the print messages in above to look "inside" the loop

0
<class 'int'>
1
<class 'int'>
2
<class 'int'>
3
<class 'int'>
4
<class 'int'>


## New material

### Numpy

- arrays vs lists [what is an array](https://numpy.org/doc/1.22/user/absolute_beginners.html#what-is-an-array)
- broadcasting

In [9]:
import numpy as np

In [10]:
tmp_list = [1, 2, 3, 4]
numpy_arr = np.array([1, 2, 3, 4])

In [11]:
# Arrays vs lists
print(tmp_list * 2)
print(numpy_arr * 2)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


#### Numpy functions

Scalar Math

|   |   |
|---|---|
|`np.add(arr,1)` | Add 1 to each array element  |
|`np.subtract(arr,2)`  | Subtract 2 from each array element  |
|`np.multiply(arr,3)`  | Multiply each array element by 3 |
|`np.divide(arr,4)`    | Divide each array element by 4 (returns `np.nan` for division by zero) |
|`np.power(arr,5)`     | Raise each array element to the 5th power | 




Vector Math

|   |   |
|---|---|
|`np.add(arr1,arr2)` | Elementwise add arr2 to arr1  |
|`np.subtract(arr1,arr2)`  | Elementwise subtract arr2 from arr1  |
|`np.multiply(arr1,arr2)`  | Elementwise multiply arr1 by arr2 |
|`np.divide(arr1,arr2)`    | Elementwise divide arr1 by arr2 |
|`np.power(arr1,arr2)`     | Elementwise raise arr1 raised to the power of arr2 | 
|`np.array_equal(arr1,arr2)`| Returns True if the arrays have the same elements and shape |
|`np.sqrt(arr)`            |  Square root of each element in the array                    |
|`np.sin(arr)`             |  Sine of each element in the array                           |
|`np.log(arr)`             |  Natural log of each element in the array                    |
|`np.abs(arr)`             |  Absolute value of each element in the array                 |
|`np.ceil(arr)`            |  Rounds up to the nearest int                                |
|`np.floor(arr)`           |  Rounds down to the nearest int                              |
|`np.round(arr)`           |  Rounds to the nearest int                                   |

#### Numpy code examples

Multidimensional arrays & shapes
How do we build n-D arrays

In [13]:
import numpy as np
tmp_array = np.zeros([2, 5])
print(tmp_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
tmp_array[1, 2] = 'a'  # Cannot assign a string to an array value once a numpy array has been initialised with numbers

ValueError: ignored

Build matrices w/ zeros, ones, arbitrary values (full)

In [ ]:
# Try np.zeros; np.ones; np.full

Slicing - by dimensions (see shape)

In [18]:
nested_list = [[i+j for i in range(5)] for j in range(5)]

In [19]:
nested_list

[[0, 1, 2, 3, 4],
 [1, 2, 3, 4, 5],
 [2, 3, 4, 5, 6],
 [3, 4, 5, 6, 7],
 [4, 5, 6, 7, 8]]

In [22]:
tmp_arr = np.array(nested_list)
print(tmp_arr)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [23]:
tmp_arr[:, 1:4]  # Doing something like this, though, is very difficult with lists

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [27]:
[r[1:4] for r in nested_list]  # Something like this would have to be done - which starts to get complicated (and inefficient)!
# This is another example of why numpy is used

[[1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6], [5, 6, 7]]

### Statistics

- Central tendancy (mean, median, mode)
- Dispersion (variance, standard deviation)
- Covariance, correlation

In [ ]:
# Example of a manual mean calculation with a for-loop, or with numpy 
sample = [54, 54, 54, 55, 56, 57, 57, 58, 58, 60, 60]

# With a for loop
sum = 0
for s in sample:
  sum += s

print(sum / len(sample))  

# With numpy
print(np.mean(sample))

56.63636363636363
56.63636363636363
